# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoadCell.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LoadCell.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eLoadCell.proto\"5\n\x08RecordId\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x16\n\x0esequenceNumber\x18\x02 \x01(\x03\"\x91\x01\n\nDeviceData\x12\x45\n\x15timeStampToDeviceData\x18\x01 \x03(\x0b\x32&.DeviceData.TimeStampToDeviceDataEntry\x1a<\n\x1aTimeStampToDeviceDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"\x84\x01\n\x0b\x43oordinates\x12<\n\x10\x64imensionToValue\x18\x01 \x03(\x0b\x32\".Coordinates.DimensionToValueEntry\x1a\x37\n\x15\x44imensionToValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbc\x01\n\x0e\x44\x65viceLocation\x12W\n\x1corientationTypeToCoordinates\x18\x01 \x03(\x0b\x32\x31.DeviceLocation.OrientationTypeToCoordinatesEntry\x1aQ\n!OrientationTypeToCoordinatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.Coordinates:\x02\x38\x01\"\xc9\x02\n\x08LoadCell\x12\x1b\n\x08recordId\x18\x01 \x01(\x0b\x32\t.RecordId\x12\n\n\x02Id\x18\x02 \x01(\t\x12\x1d\n\x02lc\x18\x03 \x03(\x0b\x32\x11.LoadCell.LcEntry\x12\r\n\x05store\x18\x04 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x05 \x01(\t\x12K\n\x19timestampToDeviceLocation\x18\x06 \x03(\x0b\x32(.LoadCell.TimestampToDeviceLocationEntry\x1a\x36\n\x07LcEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.DeviceData:\x02\x38\x01\x1aQ\n\x1eTimestampToDeviceLocationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.DeviceLocation:\x02\x38\x01\x62\x06proto3')
)




_RECORDID = _descriptor.Descriptor(
  name='RecordId',
  full_name='RecordId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='RecordId.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='RecordId.sequenceNumber', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=71,
)


_DEVICEDATA_TIMESTAMPTODEVICEDATAENTRY = _descriptor.Descriptor(
  name='TimeStampToDeviceDataEntry',
  full_name='DeviceData.TimeStampToDeviceDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DeviceData.TimeStampToDeviceDataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DeviceData.TimeStampToDeviceDataEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=219,
)

_DEVICEDATA = _descriptor.Descriptor(
  name='DeviceData',
  full_name='DeviceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStampToDeviceData', full_name='DeviceData.timeStampToDeviceData', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEVICEDATA_TIMESTAMPTODEVICEDATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=219,
)


_COORDINATES_DIMENSIONTOVALUEENTRY = _descriptor.Descriptor(
  name='DimensionToValueEntry',
  full_name='Coordinates.DimensionToValueEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Coordinates.DimensionToValueEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Coordinates.DimensionToValueEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=354,
)

_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensionToValue', full_name='Coordinates.dimensionToValue', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COORDINATES_DIMENSIONTOVALUEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=354,
)


_DEVICELOCATION_ORIENTATIONTYPETOCOORDINATESENTRY = _descriptor.Descriptor(
  name='OrientationTypeToCoordinatesEntry',
  full_name='DeviceLocation.OrientationTypeToCoordinatesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DeviceLocation.OrientationTypeToCoordinatesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DeviceLocation.OrientationTypeToCoordinatesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=545,
)

_DEVICELOCATION = _descriptor.Descriptor(
  name='DeviceLocation',
  full_name='DeviceLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orientationTypeToCoordinates', full_name='DeviceLocation.orientationTypeToCoordinates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEVICELOCATION_ORIENTATIONTYPETOCOORDINATESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=545,
)


_LOADCELL_LCENTRY = _descriptor.Descriptor(
  name='LcEntry',
  full_name='LoadCell.LcEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='LoadCell.LcEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='LoadCell.LcEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=740,
  serialized_end=794,
)

_LOADCELL_TIMESTAMPTODEVICELOCATIONENTRY = _descriptor.Descriptor(
  name='TimestampToDeviceLocationEntry',
  full_name='LoadCell.TimestampToDeviceLocationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='LoadCell.TimestampToDeviceLocationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='LoadCell.TimestampToDeviceLocationEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=796,
  serialized_end=877,
)

_LOADCELL = _descriptor.Descriptor(
  name='LoadCell',
  full_name='LoadCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recordId', full_name='LoadCell.recordId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Id', full_name='LoadCell.Id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lc', full_name='LoadCell.lc', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='store', full_name='LoadCell.store', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity', full_name='LoadCell.entity', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestampToDeviceLocation', full_name='LoadCell.timestampToDeviceLocation', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LOADCELL_LCENTRY, _LOADCELL_TIMESTAMPTODEVICELOCATIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=877,
)

_DEVICEDATA_TIMESTAMPTODEVICEDATAENTRY.containing_type = _DEVICEDATA
_DEVICEDATA.fields_by_name['timeStampToDeviceData'].message_type = _DEVICEDATA_TIMESTAMPTODEVICEDATAENTRY
_COORDINATES_DIMENSIONTOVALUEENTRY.containing_type = _COORDINATES
_COORDINATES.fields_by_name['dimensionToValue'].message_type = _COORDINATES_DIMENSIONTOVALUEENTRY
_DEVICELOCATION_ORIENTATIONTYPETOCOORDINATESENTRY.fields_by_name['value'].message_type = _COORDINATES
_DEVICELOCATION_ORIENTATIONTYPETOCOORDINATESENTRY.containing_type = _DEVICELOCATION
_DEVICELOCATION.fields_by_name['orientationTypeToCoordinates'].message_type = _DEVICELOCATION_ORIENTATIONTYPETOCOORDINATESENTRY
_LOADCELL_LCENTRY.fields_by_name['value'].message_type = _DEVICEDATA
_LOADCELL_LCENTRY.containing_type = _LOADCELL
_LOADCELL_TIMESTAMPTODEVICELOCATIONENTRY.fields_by_name['value'].message_type = _DEVICELOCATION
_LOADCELL_TIMESTAMPTODEVICELOCATIONENTRY.containing_type = _LOADCELL
_LOADCELL.fields_by_name['recordId'].message_type = _RECORDID
_LOADCELL.fields_by_name['lc'].message_type = _LOADCELL_LCENTRY
_LOADCELL.fields_by_name['timestampToDeviceLocation'].message_type = _LOADCELL_TIMESTAMPTODEVICELOCATIONENTRY
DESCRIPTOR.message_types_by_name['RecordId'] = _RECORDID
DESCRIPTOR.message_types_by_name['DeviceData'] = _DEVICEDATA
DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.message_types_by_name['DeviceLocation'] = _DEVICELOCATION
DESCRIPTOR.message_types_by_name['LoadCell'] = _LOADCELL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecordId = _reflection.GeneratedProtocolMessageType('RecordId', (_message.Message,), dict(
  DESCRIPTOR = _RECORDID,
  __module__ = 'LoadCell_pb2'
  # @@protoc_insertion_point(class_scope:RecordId)
  ))
_sym_db.RegisterMessage(RecordId)

DeviceData = _reflection.GeneratedProtocolMessageType('DeviceData', (_message.Message,), dict(

  TimeStampToDeviceDataEntry = _reflection.GeneratedProtocolMessageType('TimeStampToDeviceDataEntry', (_message.Message,), dict(
    DESCRIPTOR = _DEVICEDATA_TIMESTAMPTODEVICEDATAENTRY,
    __module__ = 'LoadCell_pb2'
    # @@protoc_insertion_point(class_scope:DeviceData.TimeStampToDeviceDataEntry)
    ))
  ,
  DESCRIPTOR = _DEVICEDATA,
  __module__ = 'LoadCell_pb2'
  # @@protoc_insertion_point(class_scope:DeviceData)
  ))
_sym_db.RegisterMessage(DeviceData)
_sym_db.RegisterMessage(DeviceData.TimeStampToDeviceDataEntry)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(

  DimensionToValueEntry = _reflection.GeneratedProtocolMessageType('DimensionToValueEntry', (_message.Message,), dict(
    DESCRIPTOR = _COORDINATES_DIMENSIONTOVALUEENTRY,
    __module__ = 'LoadCell_pb2'
    # @@protoc_insertion_point(class_scope:Coordinates.DimensionToValueEntry)
    ))
  ,
  DESCRIPTOR = _COORDINATES,
  __module__ = 'LoadCell_pb2'
  # @@protoc_insertion_point(class_scope:Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)
_sym_db.RegisterMessage(Coordinates.DimensionToValueEntry)

DeviceLocation = _reflection.GeneratedProtocolMessageType('DeviceLocation', (_message.Message,), dict(

  OrientationTypeToCoordinatesEntry = _reflection.GeneratedProtocolMessageType('OrientationTypeToCoordinatesEntry', (_message.Message,), dict(
    DESCRIPTOR = _DEVICELOCATION_ORIENTATIONTYPETOCOORDINATESENTRY,
    __module__ = 'LoadCell_pb2'
    # @@protoc_insertion_point(class_scope:DeviceLocation.OrientationTypeToCoordinatesEntry)
    ))
  ,
  DESCRIPTOR = _DEVICELOCATION,
  __module__ = 'LoadCell_pb2'
  # @@protoc_insertion_point(class_scope:DeviceLocation)
  ))
_sym_db.RegisterMessage(DeviceLocation)
_sym_db.RegisterMessage(DeviceLocation.OrientationTypeToCoordinatesEntry)

LoadCell = _reflection.GeneratedProtocolMessageType('LoadCell', (_message.Message,), dict(

  LcEntry = _reflection.GeneratedProtocolMessageType('LcEntry', (_message.Message,), dict(
    DESCRIPTOR = _LOADCELL_LCENTRY,
    __module__ = 'LoadCell_pb2'
    # @@protoc_insertion_point(class_scope:LoadCell.LcEntry)
    ))
  ,

  TimestampToDeviceLocationEntry = _reflection.GeneratedProtocolMessageType('TimestampToDeviceLocationEntry', (_message.Message,), dict(
    DESCRIPTOR = _LOADCELL_TIMESTAMPTODEVICELOCATIONENTRY,
    __module__ = 'LoadCell_pb2'
    # @@protoc_insertion_point(class_scope:LoadCell.TimestampToDeviceLocationEntry)
    ))
  ,
  DESCRIPTOR = _LOADCELL,
  __module__ = 'LoadCell_pb2'
  # @@protoc_insertion_point(class_scope:LoadCell)
  ))
_sym_db.RegisterMessage(LoadCell)
_sym_db.RegisterMessage(LoadCell.LcEntry)
_sym_db.RegisterMessage(LoadCell.TimestampToDeviceLocationEntry)


_DEVICEDATA_TIMESTAMPTODEVICEDATAENTRY._options = None
_COORDINATES_DIMENSIONTOVALUEENTRY._options = None
_DEVICELOCATION_ORIENTATIONTYPETOCOORDINATESENTRY._options = None
_LOADCELL_LCENTRY._options = None
_LOADCELL_TIMESTAMPTODEVICELOCATIONENTRY._options = None
# @@protoc_insertion_point(module_scope)
